#include "resolve.h"

void ftp_init(const char *ip, unsigned short int port);
void ftp_fini();

extern int (*f_sceNetCtlInit)(void);
extern void (*f_sceNetCtlTerm)(void);
extern int (*f_sceNetCtlGetInfo)(int code, SceNetCtlInfo *info);

extern int *sceNetErrnoLoc(void);

extern typeof(sceKernelLoadStartModule)* f_sceKernelLoadStartModule;
extern typeof(sceKernelDebugOutText)* f_sceKernelDebugOutText;
extern typeof(sceKernelUsleep)* f_sceKernelUsleep;
extern typeof(sceKernelSendNotificationRequest) * f_sceKernelSendNotificationRequest;
extern typeof(scePthreadMutexLock)* f_scePthreadMutexLock;
extern typeof(scePthreadMutexUnlock)* f_scePthreadMutexUnlock;
extern typeof(scePthreadExit)* f_scePthreadExit;
extern typeof(scePthreadMutexInit)* f_scePthreadMutexInit;
extern typeof(scePthreadCreate)* f_scePthreadCreate;
extern typeof(scePthreadMutexDestroy)* f_scePthreadMutexDestroy;
extern typeof(scePthreadJoin)* f_scePthreadJoin;
extern typeof(socket)* f_socket;
extern typeof(bind)* f_bind;
extern typeof(listen)* f_listen;
extern typeof(accept)* f_accept;
extern typeof(open)* f_open;
extern typeof(read)* f_read;
extern typeof(write)* f_write;
extern typeof(close)* f_close;
extern typeof(stat) * f_stat;
extern typeof(fstat) * f_fstat;
extern typeof(rename) * f_rename;
extern typeof(rmdir) * f_rmdir;
extern typeof(mkdir) * f_mkdir;
extern typeof(getdents) * f_getdents;
extern typeof(unlink) * f_unlink;
extern typeof(readlink) * f_readlink;
extern typeof(lseek) * f_lseek;
extern typeof(puts) * f_puts;
extern typeof(mmap) * f_mmap;
extern typeof(munmap) * f_munmap;
extern typeof(sceNetSocket) * f_sceNetSocket;
extern typeof(sceNetConnect) * f_sceNetConnect;
extern typeof(sceNetHtons) * f_sceNetHtons;
extern typeof(sceNetAccept) * f_sceNetAccept;
extern typeof(sceNetSend) * f_sceNetSend;
extern typeof(sceNetInetNtop) * f_sceNetInetNtop;
extern typeof(sceNetSocketAbort) * f_sceNetSocketAbort;
extern typeof(sceNetBind) * f_sceNetBind;
extern typeof(sceNetListen) * f_sceNetListen;
extern typeof(sceNetSocketClose) * f_sceNetSocketClose;
extern typeof(sceNetHtonl) * f_sceNetHtonl;
extern typeof(sceNetInetPton) * f_sceNetInetPton;
extern typeof(sceNetGetsockname) * f_sceNetGetsockname;
extern typeof(sceNetErrnoLoc) * f_sceNetErrnoLoc;
extern typeof(sceNetRecv) * f_sceNetRecv;
extern typeof(sceNetSetsockopt) * f_sceNetSetsockopt;
extern typeof(memset) * f_memset;
extern typeof(sprintf) * f_sprintf;
extern typeof(snprintf) * f_snprintf;
extern typeof(snprintf_s) * f_snprintf_s;
extern typeof(strcat) * f_strcat;
extern typeof(free) * f_free;
extern typeof(memcpy) * f_memcpy;
extern typeof(strcpy) * f_strcpy;
extern typeof(strncpy) * f_strncpy;
extern typeof(sscanf) * f_sscanf;
extern typeof(malloc) * f_malloc;
extern typeof(calloc) * f_calloc;
extern typeof(realloc) * f_realloc;
extern typeof(strlen) * f_strlen;
extern typeof(strdup) * f_strdup;
extern typeof(strcmp) * f_strcmp;
extern typeof(strrchr) * f_strrchr;
extern typeof(strchr) * f_strchr;
extern typeof(gmtime_s) * f_gmtime_s;
extern typeof(time) * f_time;
extern typeof(localtime) * f_localtime;
extern typeof(vsprintf) * f_vsprintf;
extern typeof(read) * f__read;
extern typeof(fork) * f_fork;
extern typeof(exit) * f_exit;

#define sce_net_errno (*f_sceNetErrnoLoc())
